spring:
  application:
    name: backend
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://ep-royal-frost-an0bni8o-pooler.c-6.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:neondb_owner}
    password: ${DATABASE_PASSWORD:npg_iEFlw98WPYyz}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

app:
  jwt:
    secret: ${JWT_SECRET:change-me-in-production-change-me-in-production}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
